# CREATE DEPLOYMENT WITH SECRET KEY
# Note: image should be already built
# kubectl create secret generic ais3uson-https-cert --from-file=cert.pem=/pathto/ais3uson/cert.pem  --from-file=privkey.pem=/pathto/ais3uson/privkey.pem  --from-file=mysql.key=/pathto/ais3uson/mysql.key
# kubectl apply -f docker/deployAis3usonCertified.yaml
# kubectl expose deployment ais3uson-certified --type=NodePort --port=48080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ais3uson-certified
  labels:
    app: ais3uson-certified
spec:
  selector:
    matchLabels:
      app: ais3uson-certified
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ais3uson-certified
    spec:
      containers:
        - name: ais3uson
          image: ais3uson:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 48080
          volumeMounts:
            - name: certificate
              mountPath: /etc/ais3uson
              readOnly: true
      volumes:
        - name: certificate
          secret:
            secretName: ais3uson-https-cert

