apiVersion: v1
kind: Pod
metadata:
  name: ais3uson-certified
spec:
  containers:
    - name: ais3uson:v2
      image: ais3uson:v2
      imagePullPolicy: Never
      ports:
        - containerPort: 48080
      volumeMounts:
        - name: certificate
          mountPath: /etc/ais3uson
          readOnly: true
  volumes:
    - name: certificate
      secret:
        secretName: ais3uson-https-cert
        # kubectl create secret generic ais3uson-https-cert --from-file=cert.pem=/pathto/ais3uson/cert.pem  --from-file=privkey.pem=/pathto/ais3uson/privkey.pem  --from-file=mysql.key=/pathto/ais3uson/mysql.key

