# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginDialog(object):
    def setupUi(self, loginDialog):
        loginDialog.setObjectName("loginDialog")
        loginDialog.resize(699, 464)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        loginDialog.setFont(font)
        loginDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(loginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(loginDialog)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(loginDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.user = myQLineEdit(loginDialog)
        self.user.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.user.setMaxLength(32)
        self.user.setClearButtonEnabled(True)
        self.user.setObjectName("user")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user)
        self.label_3 = QtWidgets.QLabel(loginDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.password = myQLineEdit(loginDialog)
        self.password.setStyleSheet("* { lineedit-password-mask-delay: 800 }")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password)
        self.stackedWidget = myQStackedWidget(loginDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.status = QtWidgets.QPlainTextEdit(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setUndoRedoEnabled(False)
        self.status.setReadOnly(True)
        self.status.setObjectName("status")
        self.verticalLayout_2.addWidget(self.status)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.page_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.pt_driver = QtWidgets.QPlainTextEdit(self.page_6)
        self.pt_driver.setObjectName("pt_driver")
        self.verticalLayout_3.addWidget(self.pt_driver)
        self.widget = QtWidgets.QWidget(self.page_6)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.sp_port = QtWidgets.QSpinBox(self.widget)
        self.sp_port.setMinimum(1024)
        self.sp_port.setMaximum(65500)
        self.sp_port.setProperty("value", 3306)
        self.sp_port.setObjectName("sp_port")
        self.horizontalLayout.addWidget(self.sp_port)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.server = QtWidgets.QLineEdit(self.widget)
        self.server.setObjectName("server")
        self.horizontalLayout.addWidget(self.server)
        self.verticalLayout_3.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.sp_dep = QtWidgets.QSpinBox(self.page_7)
        self.sp_dep.setObjectName("sp_dep")
        self.gridLayout.addWidget(self.sp_dep, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.stackedWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnEnter = QtWidgets.QDialogButtonBox(loginDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEnter.sizePolicy().hasHeightForWidth())
        self.btnEnter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnEnter.setFont(font)
        self.btnEnter.setOrientation(QtCore.Qt.Vertical)
        self.btnEnter.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnEnter.setCenterButtons(False)
        self.btnEnter.setObjectName("btnEnter")
        self.horizontalLayout_2.addWidget(self.btnEnter)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(loginDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_4.setBuddy(self.user)
        self.label_3.setBuddy(self.password)

        self.retranslateUi(loginDialog)
        self.stackedWidget.setCurrentIndex(0)
        self.btnEnter.accepted.connect(loginDialog.accept)
        self.btnEnter.rejected.connect(loginDialog.reject)
        self.pushButton.clicked.connect(self.stackedWidget.next_tab)
        QtCore.QMetaObject.connectSlotsByName(loginDialog)

    def retranslateUi(self, loginDialog):
        _translate = QtCore.QCoreApplication.translate
        loginDialog.setWindowTitle(_translate("loginDialog", "АИС ТриУСОН"))
        self.label.setText(_translate("loginDialog", "Введите ваши логин пароль для входа в систему АИС ТриУСОН:"))
        self.label_4.setText(_translate("loginDialog", "Логин:"))
        self.label_3.setText(_translate("loginDialog", "Пароль:"))
        self.label_2.setText(_translate("loginDialog", "Статус:"))
        self.label_5.setText(_translate("loginDialog", "Драйвер"))
        self.label_6.setText(_translate("loginDialog", "Порт"))
        self.label_8.setText(_translate("loginDialog", "Сервер:"))
        self.label_7.setText(_translate("loginDialog", "№ отделения"))
        self.pushButton.setText(_translate("loginDialog", "info"))
from widgets.custumQWidgets import myQLineEdit, myQStackedWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginDialog = QtWidgets.QDialog()
    ui = Ui_loginDialog()
    ui.setupUi(loginDialog)
    loginDialog.show()
    sys.exit(app.exec_())
