#!/bin/bash
#############################
# goto work dir
# ---------------------------
default_path="$1"
if [[ "$1" == "" ]] ; then
  default_path=../src
fi
#pushd "$default_path" || echo "can't find $default_path" && exit
#############################
# function inotifywait daemon
# ---------------------------
function run() {
  #set -x
  file="$1"
  fname="$(basename $file)"
  basedir=${file/$fname}
  fname=${fname/.ui}
  pysideuic=$(type -p pyside2-uic)
  temp1=$(mktemp)
#  echo $temp1
  while inotifywait -e close_write "$file"; do
    pyuic5 "${file}" > $temp1
    cur_file="$basedir/autogenerated/${fname}_pyqt5.py"
    lc=$(diff $cur_file $temp1 | grep "^>" -c)
    if [[ $lc -gt 2 ]]; then
      cp -f "$temp1" "$cur_file"
      echo "updated $cur_file"
    fi

    python3 "$pysideuic" "${file}" > $temp1
    cur_file="$basedir/autogenerated/${fname}_pyside2.py"
    lc=$(diff $cur_file $temp1 | grep "^>" -c)
    if [[ $lc -gt 2 ]]; then
      cp -f "$temp1" "$cur_file"
      echo "updated $cur_file"
    fi
  #set +x
  done
}
#############################
# find files and assign runner
# ---------------------------
ls $default_path/*.ui | while read -r file
  do
    echo "Running inotifywait for $file"
    run "$file" &
done
