cd ..\widgets_ui
rem mkdir "autogenerated"
..\venvqt\Scripts\pyuic5.exe -x main_window.ui    -o autogenerated\main_window_pyqt5.py
..\venvqt\Scripts\pyuic5.exe -x login_dialog.ui   -o autogenerated\login_dialog_pyqt5.py
..\venvqt\Scripts\pyuic5.exe -x qcSelectPeriod.ui -o autogenerated\qcSelectPeriod_pyqt5.py
..\venvqt\Scripts\pyuic5.exe -x qcSelectReport.ui -o autogenerated\qcSelectReport_pyqt5.py

..\venv39-32\Scripts\pyside2-uic.exe main_window.ui       > autogenerated\main_window_pyside2.py
..\venv39-32\Scripts\pyside2-uic.exe login_dialog.ui      > autogenerated\login_dialog_pyside2.py
..\venv39-32\Scripts\pyside2-uic.exe qcSelectPeriod.ui    > autogenerated\qcSelectPeriod_pyside2.py
..\venv39-32\Scripts\pyside2-uic.exe qcSelectReport.ui    > autogenerated\qcSelectReport_pyside2.py

..\venv\Scripts\pyside6-uic.exe main_window.ui       > autogenerated\main_window_pyside6.py
..\venv\Scripts\pyside6-uic.exe login_dialog.ui      > autogenerated\login_dialog_pyside6.py
..\venv\Scripts\pyside6-uic.exe qcSelectPeriod.ui    > autogenerated\qcSelectPeriod_pyside6.py
..\venv\Scripts\pyside6-uic.exe qcSelectReport.ui    > autogenerated\qcSelectReport_pyside6.py

cd ..\tools
