#!/bin/bash
pushd ../widgets_ui || `echo "can't find ../widgets_ui dir" && exit`
  #mkdir "autogenerated"
#  pysideuic=`type -p pyside2-uic`
  pysideuic=`type -p pyside6-uic`
  /usr/bin/pyuic5        main_window.ui    > autogenerated/main_window_pyqt5.py
  python3 $pysideuic     main_window.ui    > autogenerated/main_window_pyside2.py
  /usr/bin/pyuic5        login_dialog.ui   > autogenerated/login_dialog_pyqt5.py
  python3 $pysideuic     login_dialog.ui   > autogenerated/login_dialog_pyside2.py
  /usr/bin/pyuic5        qcSelectPeriod.ui > autogenerated/qcSelectPeriod_pyqt5.py
  python3 $pysideuic     qcSelectPeriod.ui > autogenerated/qcSelectPeriod_pyside2.py
  /usr/bin/pyuic5        qcSelectReport.ui > autogenerated/qcSelectReport_pyqt5.py
  python3 $pysideuic     qcSelectReport.ui > autogenerated/qcSelectReport_pyside2.py
echo "done"
popd
