apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.ais3uson.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.ais3uson.service: adminer
  strategy: {}
  template:
    metadata:
      labels:
        io.ais3uson.network/backend: "true"
        io.ais3uson.network/frontend: "true"
        io.ais3uson.service: adminer
    spec:
      containers:
        - image: adminer
          name: adminer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
