apiVersion: v1
kind: Service
metadata:
  labels:
    io.ais3uson.service: adminer
  name: adminer
spec:
  type: NodePort
  ports:
    - nodePort: 30800
      name: adminer-port
      port: 8080
      targetPort: 8080
  selector:
    io.ais3uson.service: adminer
status:
  loadBalancer: { }
