apiVersion: v1
kind: Service
metadata:
  labels:
    io.ais3uson.service: ais3uson
  name: ais3uson
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30480
      name: ais3uson-port
      port: 48080
      targetPort: 48080
    - nodePort: 30481 # optional port for testing
      name: ais3uson-debug-port
      port: 48081
      targetPort: 48081
  selector:
    io.ais3uson.service: ais3uson
status:
  loadBalancer: { }
