apiVersion: v1
kind: Service
metadata:
  labels:
    io.ais3uson.service: aismysql
  name: aismysql
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30306
      port: 3307
      targetPort: 3306
  selector:
    io.ais3uson.service: aismysql
status:
  loadBalancer: { }
