apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-aismysql-volume
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: ais-mysql-role
              operator: In
              values:
                - data
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/ais-mysql-data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
