apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aismysql-volume
  labels:
    io.ais3uson.service: ais-mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: pv-aismysql-volume